<?php

/**
 * Implement hook_menu().
 */
function dexp_page_elements_menu() {
  $items = array();
  $items['admin/drupalexp/dexp_page_elements'] = array(
      'title' => 'Page title settings',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('dexp_page_elements_admin_settings'),
      'access arguments' => array('administer onthisdate settings'),
      'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function dexp_page_elements_admin_settings() {
  $form['dexp_page_title_separator'] = array(
      '#type' => 'textfield',
      '#title' => t('Page subtitle separator'),
      '#description' => t('The string separator between title and subtitle.<br/>Example title: TITLE HERE') . ' ' . variable_get('dexp_page_title_separator', '~') . t(' some more details as subtitle'),
      '#default_value' => variable_get('dexp_page_title_separator', '~'),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_preprocess_page().
 */
function dexp_page_elements_preprocess_page(&$vars) {
  if (!path_is_admin(current_path())) {
    $vars['breadcrumb'] = '';
    $vars['title'] = '';
  }
}

/**
 * Implements hook_block_info().
 */
function dexp_page_elements_block_info() {
  $blocks['dexp_page_elements_breadcrumb'] = array(
      'info' => t('DrupalExp Breadcrumb'),
      'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['dexp_page_elements_page_title'] = array(
      'info' => t('DrupalExp Page Title'),
      'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dexp_page_elements_block_view($delta) {
  $block = array();
  switch ($delta) {
    case 'dexp_page_elements_breadcrumb':
      $block['content'] = array(
          '#pre_render' => array('dexp_page_elements_prerender_breadcrumb'),
          '#theme' => 'breadcrumb',
      );
      break;
    case 'dexp_page_elements_page_title':
      $separator = variable_get('dexp_page_title_separator', '~');
      $title = drupal_get_title();
      if (empty($title))
        return '';
      if ($separator) {
        $titles = explode($separator, $title, 2);
      } else {
        $titles = array($title);
      }
      $block['content'] = '<h1 class="page_title">' . trim($titles[0]) . '</h1>';
      if (isset($titles[1])) {
        $block['content'] .= '<p class="page_subtitle">' . trim($titles[1]) . '</p>';
        drupal_set_title(trim($titles[0]));
        $block['content'] = '<div class="page_title_has_sub">' . $block['content'] . '</div>';
      } else {
        $block['content'] = '<div class="page_title_no_sub">' . $block['content'] . '</div>';
      }
      break;
  }
  if ($delta == 'superhero_breadcrumb') {
    $block['content'] = array(
        '#pre_render' => array('superhero_breadcrumb_prerender_breadcrumb'),
        '#theme' => 'breadcrumb',
    );
  }
  return $block;
}

function dexp_page_elements_prerender_breadcrumb($element) {
  $element['#breadcrumb'] = drupal_get_breadcrumb();
  if(is_array($element['#breadcrumb'])){
      foreach($element['#breadcrumb'] as $k=>$v){
          if(empty($v)){
              unset($element['#breadcrumb'][$k]);
          }
      }
  }
  if (empty($element['#breadcrumb']))
    return array();
  return $element;
}